#!/bin/bash

NAME="${1}"
COUNT=$(docker ps -qa --filter "label=app=crashplan" | wc -l)
VNC_PORT=$((5900 + COUNT))
NOVNC_PORT=$((6080 + COUNT))

docker run -d \
    --name="crashplan-${NAME}" \
    --restart=unless-stopped \
    --label=app=crashplan \
    --label="backup=${NAME}" \
    -e NOVNC=true \
    -p ${VNC_PORT}:5900 \
    -p ${NOVNC_PORT}:6080 \
    -v /media:/media \
    -v /:/rootfs \
    trapexit/crashplan:1.2
if [ $? ]; then
    echo "novnc url: http://localhost:${NOVNC_PORT}/vnc.html?autoconnect=true&resize=scale"
    echo "vnc port: ${VNC_PORT}"
fi
