#!/bin/bash

exec 2>&1

TARGETDIR=/opt/crashplan
PATH=$PATH:/opt/java/bin
CLASSPATH="${TARGETDIR}/lib/com.backup42.desktop.jar:${TARGETDIR}/lang"

source "${TARGETDIR}/bin/run.conf"

cd "${TARGETDIR}"
exec java \
    -Dfile.encoding=UTF-8 \
    -Dapp=CrashPlanService \
    -DappBaseName=CrashPlan \
    -Xms20m \
    -Xmx1024m \
    -Dsun.net.inetaddr.ttl=300 \
    -Dnetworkaddress.cache.ttl=300 \
    -Dsun.net.inetaddr.negative.ttl=0 \
    -Dnetworkaddress.cache.negative.ttl=0 \
    -Dc42.native.md5.enabled=false \
    -classpath "$CLASSPATH" \
    com.backup42.service.CPService
