#!/bin/bash

exec 2>&1

TARGETDIR=/opt/crashplan
PATH=$PATH:/opt/java/bin
CLASSPATH="${TARGETDIR}/lib/com.backup42.desktop.jar:${TARGETDIR}/lang"

source "${TARGETDIR}/bin/run.conf"

cd "${TARGETDIR}"
exec java \
    ${SRV_JAVA_OPTS} \
    -classpath "$CLASSPATH" \
    com.backup42.service.CPService
