#!/bin/bash

/tmp/setup/init

/tmp/setup/install-tigervnc
/tmp/setup/install-novnc
/tmp/setup/install-java
/tmp/setup/install-crashplan
/tmp/setup/install-xserver
/tmp/setup/install-rootfs

/tmp/setup/cleanup
